### ISSUE TITLE
What's the status of this spec and webpack support?

### ISSUE THREAD

**Issue by fix-fix** [webpack/concord#6]
In README it says:

> webpack 2.x will support concord. Loaders will get the internal preprocessing format for concord with webpack.

but it is definitely not the case as of current webpack version 2.3.

Will it be implemented in later 2.x versions or is it abandoned?

**Comment by jquense** [comment]
The resolution bits _are_ implemented in `enhanced-resolve` which means its in webpack2 automatically. The mimetype bits of mapping those configs to loaders is not there however. We use (😱 ) the concord resolution bits tho in our monorepo packages or ease of development, mapping the requests to `package/lib/foo` to `package/src/foo` and letting the top level webpack app handle compilation
